'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';

// 20개국 언어별 AI 면책 고지 동의 데이터
const disclaimerTranslations: Record<string, { title: string; backBtn: string; intro: string; sections: { title: string; content: string | string[] }[] }> = {
  ko: {
    title: 'AI 생성 콘텐츠 책임 및 할루시네이션 면책 고지 동의',
    backBtn: '돌아가기',
    intro: '서비스는 생성형 인공지능(AI) 기술을 활용하여 설문, 퀴즈 및 다양한 콘텐츠를 생성합니다. 회원은 아래 사항을 충분히 이해하고 이에 동의합니다.',
    sections: [
      {
        title: '1. AI 기술의 특성',
        content: [
          '① AI 생성 결과는 확률 기반의 기술을 이용하여 생성됩니다.',
          '② AI가 생성하는 답변 및 콘텐츠는 정확성, 완전성, 최신성, 적합성을 항상 보장하지 않습니다.',
          '③ 동일한 질문이라도 서로 다른 결과가 생성될 수 있습니다.'
        ]
      },
      {
        title: '2. 할루시네이션(환각 현상)',
        content: [
          '• AI는 실제 사실과 다른 정보 또는 존재하지 않는 정보를 생성할 수 있습니다.',
          '• 회원은 AI 생성 결과를 반드시 직접 확인하여야 합니다.'
        ]
      },
      {
        title: '3. 전문적인 판단의 제한',
        content: [
          'AI 생성 결과는 참고자료일 뿐이며 다음 사항의 단독 근거로 사용하여서는 안 됩니다:',
          '• 의료적 판단',
          '• 법률 자문',
          '• 세무 상담',
          '• 투자 및 금융 의사결정',
          '• 계약 체결',
          '• 기타 전문적인 판단이 필요한 사항',
          '필요한 경우 반드시 해당 분야의 전문가와 상담하시기 바랍니다.'
        ]
      },
      {
        title: '4. AI 입력 정보',
        content: [
          '회원은 AI 입력창에 다음 정보를 입력하지 않도록 주의하여야 합니다:',
          '• 주민등록번호, 여권번호, 운전면허번호',
          '• 금융정보, 비밀번호',
          '• 의료정보, 민감정보',
          '• 영업비밀, 타인의 개인정보',
          '회원이 이를 입력하여 발생하는 손해는 회원 본인의 책임입니다.'
        ]
      },
      {
        title: '5. AI 생성 콘텐츠의 활용',
        content: [
          '① AI 생성 결과를 활용하거나 배포하는 경우 모든 책임은 회원에게 있습니다.',
          '② AI 생성 결과가 제3자의 저작권, 상표권, 초상권, 개인정보 또는 기타 권리를 침해하지 않는지 회원이 직접 확인하여야 합니다.',
          '③ 대한민국 저작권법 및 관계 법령에 따라 AI 생성 결과의 권리관계는 개별 사안에 따라 달라질 수 있습니다.'
        ]
      },
      {
        title: '6. 책임의 제한',
        content: [
          '① 운영자는 AI 생성 결과의 정확성, 완전성, 신뢰성, 적법성 또는 특정 목적에의 적합성을 보증하지 않습니다.',
          '② 회원이 AI 생성 결과를 이용하여 발생한 직·간접적 손해에 대하여 운영자는 고의 또는 중대한 과실이 없는 한 책임을 부담하지 않습니다.'
        ]
      },
      {
        title: '7. 불법 콘텐츠 생성 제한',
        content: [
          '서비스는 다음과 같은 콘텐츠의 생성을 제한하거나 거부할 수 있습니다:',
          '• 불법행위를 조장하는 콘텐츠, 명예훼손 콘텐츠, 저작권 침해 콘텐츠',
          '• 개인정보 침해 콘텐츠, 음란물, 혐오 및 차별 콘텐츠',
          '• 악성코드 생성, 해킹 지원 콘텐츠, 관계 법령에 위반되는 콘텐츠'
        ]
      },
      {
        title: '8. AI 서비스 변경',
        content: '운영자는 AI 모델 변경, 성능 개선 또는 보안상의 필요에 따라 AI 서비스의 기능이나 생성 결과의 특성이 변경될 수 있습니다.'
      },
      {
        title: '9. 최종 확인',
        content: '회원은 AI 생성 결과를 최종적으로 검토하고 활용 여부를 스스로 결정하여야 하며, 중요한 의사결정의 근거로 사용할 경우 발생하는 책임은 회원 본인에게 있습니다.'
      }
    ]
  },
  en: {
    title: 'AI Generated Content Liability & Hallucination Disclaimer Consent',
    backBtn: 'Go Back',
    intro: 'The service utilizes generative artificial intelligence (AI) technology to generate surveys, quizzes, and various contents. Members fully understand and agree to the following terms.',
    sections: [
      {
        title: '1. Characteristics of AI Technology',
        content: ['① AI-generated results are produced using probability-based technology.', '② Answers and contents generated by AI do not always guarantee accuracy, completeness, timeliness, or suitability.', '③ Different results may be produced even for the same question.']
      },
      {
        title: '2. Hallucination Phenomenon',
        content: ['• AI may generate information that differs from actual facts or non-existent information.', '• Members must directly verify AI-generated results.']
      },
      {
        title: '3. Limitation of Professional Judgment',
        content: ['AI-generated results are for reference only and should not be used as the sole basis for:', '• Medical judgments', '• Legal advice', '• Tax consultation', '• Investment and financial decisions', '• Contract conclusions', '• Other matters requiring professional judgment', 'Please consult with experts in the respective field if necessary.']
      },
      {
        title: '4. AI Input Information',
        content: ['Members must exercise caution not to input the following information into AI input fields:', '• ID numbers, passport numbers, driver license numbers', '• Financial info, passwords', '• Medical info, sensitive info', '• Trade secrets, others personal info', 'Damages arising from inputting such information are solely the members responsibility.']
      },
      {
        title: '5. Use of AI-Generated Content',
        content: ['① All responsibility for utilizing or distributing AI-generated results lies with the member.', '② Members must directly verify whether AI results infringe upon third-party copyrights, trademark rights, portrait rights, personal info, or other rights.', '③ Rights relations of AI results may vary depending on individual cases according to applicable copyright laws.']
      },
      {
        title: '6. Limitation of Liability',
        content: ['① The operator does not guarantee accuracy, completeness, reliability, legality, or fitness for a particular purpose of AI results.', '② The operator shall not be liable for direct or indirect damages incurred by members using AI results, barring willful misconduct or gross negligence.']
      },
      {
        title: '7. Restriction on Illegal Content Generation',
        content: ['The service may restrict or refuse the generation of contents such as:', '• Content promoting illegal acts, defamation, copyright infringement', '• Personal info infringement, pornography, hate and discriminatory content', '• Malware creation, hacking support content, content violating related laws']
      },
      {
        title: '8. Changes to AI Services',
        content: 'The operator may change the functions of the AI service or characteristics of results due to AI model changes, performance improvements, or security needs.'
      },
      {
        title: '9. Final Verification',
        content: 'Members must review AI-generated results and independently decide whether to utilize them. Responsibility for using them as a basis for important decisions rests with the member.'
      }
    ]
  },
  ja: {
    title: 'AI生成コンテンツの責任およびハルシネーション免責事項への同意',
    backBtn: '戻る',
    intro: '当サービスは、生成AI（人工知能）技術を活用してアンケート、クイズ、その他のコンテンツを生成します。会員は以下の内容を十分に理解し、これに同意するものとします。',
    sections: [
      {
        title: '1. AI技術の特性',
        content: ['① AIの生成結果は確率ベースの技術を使用して生成されます。', '② AIが生成する回答およびコンテンツは、正確性、完全性、最新性、適合性を常に保証するものではありません。', '③ 同じ質問であっても異なる結果が生成される場合があります。']
      },
      {
        title: '2. ハルシネーション（幻覚現象）',
        content: ['• AIは、実際の事実とは異なる情報や存在しない情報を生成する可能性があります。', '• 会員は、AIの生成結果を必ずご自身で直接確認する必要があります。']
      },
      {
        title: '3. 専門的判断の制限',
        content: ['AIの生成結果は参考資料に過ぎず、以下の事項の単独の根拠として使用してはなりません：', '• 医療的判断', '• 法律相談', '• 税務相談', '• 投資および金融の意思決定', '• 契約の締結', '• その他専門的判断を要する事項', '必要な場合は、必ず各分野の専門家にご相談ください。']
      },
      {
        title: '4. AIへの入力情報',
        content: ['会員は、AIの入力欄に以下の情報を入力しないよう注意しなければなりません：', '• 身分証明書番号、パスポート番号、運転免許証番号', '• 金融情報、パスワード', '• 医療情報、機微情報', '• 営業秘密、他人の個人情報', '会員がこれらを入力したことにより発生した損害は、会員本人の責任となります。']
      },
      {
        title: '5. AI生成コンテンツの活用',
        content: ['① AI生成結果を活用または配布する場合、すべての責任は会員にあります。', '② AI生成結果が第三者の著作権、商標権、肖像権、プライバシー、その他の権利を侵害していないか、会員本人が直接確認しなければなりません。', '③ 関連法令等に基づき、AI生成結果の権利関係は個別事案によって異なる場合があります。']
      },
      {
        title: '6. 責任の制限',
        content: ['① 運営者は、AI生成結果の正確性、完全性、信頼性、適法性、または特定目的への適合性を保証しません。', '② 会員がAI生成結果を利用したことにより発生した直接的・間接的損害について、運営者に故意または重大な過失がない限り、責任を負わないものとします。']
      },
      {
        title: '7. 違法コンテンツの生成制限',
        content: ['サービスは、以下のようなコンテンツの生成を制限または拒否する場合があります：', '• 違法行為を助長するコンテンツ、名誉毀損コンテンツ、著作権侵害コンテンツ', '• 個人情報侵害コンテンツ、ポルノ、ヘイトスピーチおよび差別的コンテンツ', '• マルウェアの生成、ハッキング支援コンテンツ、関連法令に違反するコンテンツ']
      },
      {
        title: '8. AIサービスの変更',
        content: '運営者は、AIモデルの変更、パフォーマンスの向上、またはセキュリティ上の必要性に応じて、AIサービスの機能や生成結果の特性を変更する場合があります。'
      },
      {
        title: '9. 最終確認',
        content: '会員はAI生成結果を最終的に確認し、活用するかどうかを自ら判断する必要があり、重要な意思決定の根拠として使用した場合に生じる責任は会員本人に帰属します。'
      }
    ]
  },
  zh: {
    title: 'AI生成内容责任及幻觉免责声明同意书',
    backBtn: '返回',
    intro: '本服务利用生成式人工智能（AI）技术生成问卷、测验及各种内容。会员已充分理解并同意以下事项。',
    sections: [
      {
        title: '1. AI技术的特性',
        content: ['① AI生成结果是基于概率技术生成的。', '② AI生成的回答和内容并不总是保证准确性、完整性、最新性或适宜性。', '③ 即使是相同的问题，也可能会产生不同的结果。']
      },
      {
        title: '2. 幻觉现象',
        content: ['• AI可能会生成与实际事实不符的信息或不存在的信息。', '• 会员必须亲自对AI生成结果进行核实。']
      },
      {
        title: '3. 专业判断的限制',
        content: ['AI生成结果仅供参考，不得作为以下事项的唯一依据：', '• 医疗判断', '• 法律咨询', '• 税务咨询', '• 投资及金融决策', '• 签订合同', '• 其他需要专业判断的事项', '如有必要，请务必咨询相关领域的专家。']
      },
      {
        title: '4. AI输入信息',
        content: ['会员在AI输入框中输入信息时，应注意避免输入以下内容：', '• 身份证号、护照号、驾照号', '• 金融信息、密码', '• 医疗信息、敏感信息', '• 商业秘密、他人的个人信息', '因会员输入上述信息而产生的损失由会员本人承担。']
      },
      {
        title: '5. AI生成内容的利用',
        content: ['① 利用或分发AI生成结果的所有责任由会员承担。', '② 会员必须亲自确认AI生成结果是否侵犯了第三方的著作权、商标权、肖像权、个人信息或其他权利。', '③ 根据相关法律法规，AI生成结果的权利归属可能会因具体案件而异。']
      },
      {
        title: '6. 责任限制',
        content: ['① 运营方不保证AI生成结果的准确性、完整性、可靠性、合法性或对特定目的的适用性。', '② 对于会员因使用AI生成结果而遭受的直接或间接损失，除运营方存在故意或重大过失外，运营方不承担责任。']
      },
      {
        title: '7. 非法内容生成限制',
        content: ['本服务可限制或拒绝生成以下内容：', '• 助长违法行为的内容、诽谤内容、侵犯版权内容', '• 侵犯个人隐私内容、色情内容、仇恨及歧视内容', '• 生成恶意软件、提供黑客协助内容、违反相关法律法规的内容']
      },
      {
        title: '8. AI服务的变更',
        content: '运营方可根据AI模型的变更、性能提升或安全需求，对AI服务的功能或生成结果的特性进行更改。'
      },
      {
        title: '9. 最终确认',
        content: '会员必须对AI生成结果进行最终审查，并自行决定是否使用。将其作为重要决策依据时所产生的责任由会员本人承担。'
      }
    ]
  },
  es: {
    title: 'Consentimiento de Exención de Responsabilidad por Contenido Generado por IA y Alucinaciones',
    backBtn: 'Volver',
    intro: 'El servicio utiliza tecnología de inteligencia artificial (IA) generativa para crear encuestas, cuestionarios y diversos contenidos. Los miembros comprenden plenamente y aceptan los siguientes términos.',
    sections: [
      { title: '1. Características de la tecnología de IA', content: ['① Los resultados generados por IA se producen utilizando tecnología basada en probabilidades.', '② Las respuestas y contenidos generados por IA no siempre garantizan precisión, integridad, actualización o idoneidad.', '③ Se pueden producir resultados diferentes incluso para la misma pregunta.'] },
      { title: '2. Fenómeno de alucinación', content: ['• La IA puede generar información que difiere de los hechos reales o información inexistente.', '• Los miembros deben verificar personalmente los resultados generados por la IA.'] },
      { title: '3. Limitación del juicio profesional', content: ['Los resultados generados por IA son solo de referencia y no deben utilizarse como base única para:', '• Juicios médicos', '• Asesoramiento legal', '• Asesoramiento fiscal', '• Decisiones de inversión y financieras', '• Conclusión de contratos', '• Otros asuntos que requieran juicio profesional', 'Consulte con expertos en el campo correspondiente si es necesario.'] },
      { title: '4. Información de entrada de IA', content: ['Los miembros deben tener cuidado de no ingresar la siguiente información en los campos de entrada de IA:', '• Números de identificación, pasaporte, licencia de conducir', '• Información financiera, contraseñas', '• Información médica, información confidencial', '• Secretos comerciales, información personal de terceros', 'Los daños derivados de la introducción de dicha información son responsabilidad exclusiva del miembro.'] },
      { title: '5. Uso de contenido generado por IA', content: ['① Toda la responsabilidad por el uso o distribución de los resultados generados por IA recae en el miembro.', '② Los miembros deben verificar directamente si los resultados de la IA infringen los derechos de autor, marcas registradas, derechos de imagen, información personal u otros derechos de terceros.', '③ Las relaciones de derechos de los resultados de la IA pueden variar según cada caso conforme a las leyes de propiedad intelectual aplicables.'] },
      { title: '6. Limitación de responsabilidad', content: ['① El operador no garantiza la precisión, integridad, fiabilidad, legalidad o idoneidad para un propósito particular de los resultados de la IA.', '② El operador no será responsable de los daños directos o indirectos incurridos por los miembros que utilicen los resultados de la IA, salvo en caso de dolo o negligencia grave.'] },
      { title: '7. Restricción de generación de contenido ilegal', content: ['El servicio puede restringir o rechazar la generación de contenidos tales como:', '• Contenido que promueva actos ilegales, difamación, infracción de derechos de autor', '• Contenido de violación de privacidad, pornografía, contenido de odio y discriminatorio', '• Creación de malware, contenido de apoyo a la piratería, contenido que viole las leyes aplicables'] },
      { title: '8. Cambios en el servicio de IA', content: 'El operador puede cambiar las funciones del servicio de IA o las características de los resultados debido a cambios en el modelo de IA, mejoras de rendimiento o necesidades de seguridad.' },
      { title: '9. Verificación final', content: 'Los miembros deben revisar los resultados generados por la IA y decidir de manera independiente si los utilizan; la responsabilidad de utilizarlos como base para decisiones importantes recae en el propio miembro.' }
    ]
  },
  fr: {
    title: 'Consentement à la clause de non-responsabilité concernant le contenu généré par IA et les hallucinations',
    backBtn: 'Retour',
    intro: 'Le service utilise la technologie de l’intelligence artificielle (IA) générative pour créer des sondages, des quiz et divers contenus. Les membres comprennent parfaitement et acceptent les conditions suivantes.',
    sections: [
      { title: '1. Caractéristiques de la technologie IA', content: ['① Les résultats générés par IA sont produits à l’aide d’une technologie basée sur les probabilités.', '② Les réponses et contenus générés par l’IA ne garantissent pas toujours l’exactitude, l’exhaustivité, l’actualité ou l’adéquation.', '③ Des résultats différents peuvent être produits même pour une même question.'] },
      { title: '2. Phénomène d’hallucination', content: ['• L’IA peut générer des informations différentes des faits réels ou des informations inexistantes.', '• Les membres doivent vérifier personnellement les résultats générés par l’IA.'] },
      { title: '3. Limitation du jugement professionnel', content: ['Les résultats générés par l’IA sont fournis à titre de référence uniquement et ne doivent pas être utilisés comme seule base pour :', '• Des jugements médicaux', '• Des conseils juridiques', '• Des conseils fiscaux', '• Des décisions d’investissement et financières', '• La conclusion de contrats', '• Toute autre question nécessitant un jugement professionnel', 'Veuillez consulter des experts dans le domaine concerné si nécessaire.'] },
      { title: '4. Informations saisies dans l’IA', content: ['Les membres doivent veiller à ne pas saisir les informations suivantes dans les champs de saisie de l’IA :', '• Numéros d’identification, numéros de passeport, numéros de permis de conduire', '• Informations financières, mots de passe', '• Informations médicales, informations sensibles', '• Secrets commerciaux, informations personnelles de tiers', 'Les dommages résultant de la saisie de telles informations relèvent de la seule responsabilité du membre.'] },
      { title: '5. Utilisation du contenu généré par l’IA', content: ['① L’entière responsabilité de l’utilisation ou de la diffusion des résultats générés par l’IA incombe au membre.', '② Les membres doivent vérifier directement si les résultats de l’IA violent les droits d’auteur, les marques, les droits à l’image, les informations personnelles ou d’autres droits de tiers.', '③ Les relations de droits relatives aux résultats de l’IA peuvent varier selon les cas individuels conformément aux lois applicables.'] },
      { title: '6. Limitation de responsabilité', content: ['① L’exploitant ne garantit pas l’exactitude, l’exhaustivité, la fiabilité, la légalité ou l’adéquation à un usage particulier des résultats de l’IA.', '② L’exploitant ne pourra être tenu responsable des dommages directs ou indirects subis par les membres utilisant les résultats de l’IA, sauf en cas de faute intentionnelle ou de négligence lourde.'] },
      { title: '7. Restriction sur la génération de contenus illégaux', content: ['Le service peut restreindre ou refuser la génération de contenus tels que :', '• Du contenu promouvant des actes illégaux, de la diffamation, des violations du droit d’auteur', '• Du contenu portant atteinte à la vie privée, de la pornographie, du contenu haineux et discriminatoire', '• La création de logiciels malveillants, du contenu d’aide au piratage, du contenu violant les lois applicables'] },
      { title: '8. Modifications du service IA', content: 'L’exploitant peut modifier les fonctionnalités du service IA ou les caractéristiques des résultats en raison de changements de modèle IA, d’améliorations des performances ou de nécessités de sécurité.' },
      { title: '9. Vérification finale', content: 'Les membres doivent examiner les résultats générés par l’IA et décider de manière autonome de leur utilisation ; la responsabilité de leur utilisation comme base de décisions importantes incombe au membre lui-même.' }
    ]
  },
  de: {
    title: 'Einwilligung zum Haftungsausschluss für KI-generierte Inhalte und Halluzinationen',
    backBtn: 'Zurück',
    intro: 'Der Dienst nutzt generative künstliche Intelligenz (KI), um Umfragen, Quiz und verschiedene Inhalte zu erstellen. Die Mitglieder haben die folgenden Bedingungen vollständig verstanden und stimmen ihnen zu.',
    sections: [
      { title: '1. Eigenschaften der KI-Technologie', content: ['① KI-generierte Ergebnisse werden mithilfe wahrscheinlichkeitssbasierter Technologie erzeugt.', '② Von der KI generierte Antworten und Inhalte garantieren nicht immer Genauigkeit, Vollständigkeit, Aktualität oder Eignung.', '③ Selbst bei derselben Frage können unterschiedliche Ergebnisse erzielt werden.'] },
      { title: '2. Halluzinationsphänomen', content: ['• KI kann Informationen erzeugen, die von tatsächlichen Fakten abweichen oder nicht existieren.', '• Mitglieder müssen KI-generierte Ergebnisse unbedingt eigenständig überprüfen.'] },
      { title: '3. Einschränkung professioneller Urteile', content: ['KI-generierte Ergebnisse dienen nur als Referenz und dürfen nicht als alleinige Grundlage für Folgendes verwendet werden:', '• Medizinische Entscheidungen', '• Rechtsberatung', '• Steuerberatung', '• Investitions- und Finanzentscheidungen', '• Vertragsabschlüsse', '• Andere Angelegenheiten, die professionelles Urteilsvermögen erfordern', 'Konsultieren Sie bei Bedarf unbedingt Experten auf dem jeweiligen Gebiet.'] },
      { title: '4. KI-Eingabeinformationen', content: ['Mitglieder müssen darauf achten, folgende Informationen nicht in KI-Eingabefelder einzugeben:', '• Ausweisnummern, Passnummern, Führerscheinnummern', '• Finanzinformationen, Passwörter', '• Medizinische Informationen, sensible Daten', '• Geschäftsgeheimnisse, personenbezogene Daten anderer', 'Schäden, die durch die Eingabe solcher Informationen entstehen, liegen in der alleinigen Verantwortung des Mitglieds.'] },
      { title: '5. Nutzung KI-generierter Inhalte', content: ['① Die volle Verantwortung für die Nutzung oder Verbreitung KI-generierter Ergebnisse liegt beim Mitglied.', '② Mitglieder müssen direkt überprüfen, ob KI-Ergebnisse Urheberrechte, Markenrechte, Persönlichkeitsrechte, personenbezogene Daten oder andere Rechte Dritter verletzen.', '③ Die Rechtsverhältnisse von KI-Ergebnissen können je nach Einzelfall gemäß geltendem Recht variieren.'] },
      { title: '6. Haftungsbeschränkung', content: ['① Der Betreiber garantiert weder die Genauigkeit, Vollständigkeit, Zuverlässigkeit, Rechtmäßigkeit noch die Eignung für einen bestimmten Zweck der KI-Ergebnisse.', '② Der Betreiber haftet nicht für direkte oder indirecte Schäden, die Mitgliedern durch die Nutzung von KI-Ergebnissen entstehen, es sei denn, es liegt Vorsatz oder grobe Fahrlässigkeit vor.'] },
      { title: '7. Beschränkung der Erstellung illegaler Inhalte', content: ['Der Dienst kann die Erstellung folgender Inhalte einschränken oder ablehnen:', '• Inhalte, die illegale Handlungen fördern, Verleumdung, Urheberrechtsverletzungen', '• Verletzung der Privatsphäre, Pornografie, Hass- und diskriminierende Inhalte', '• Erstellung von Schadsoftware, Unterstützung von Hacking, Verstöße gegen geltendes Recht'] },
      { title: '8. Änderungen des KI-Dienstes', content: 'Der Betreiber kann die Funktionen des KI-Dienstes oder die Eigenschaften der Ergebnisse aufgrund von KI-Modelländerungen, Leistungsverbesserungen oder Sicherheitsanforderungen ändern.' },
      { title: '9. Endgültige Überprüfung', content: 'Mitglieder müssen KI-generierte Ergebnisse abschließend prüfen und eigenständig entscheiden, ob sie diese verwenden; die Verantwortung für die Verwendung als Grundlage für wichtige Entscheidungen liegt beim Mitglied selbst.' }
    ]
  },
  ru: {
    title: 'Согласие с отказом от ответственности за контент, созданный ИИ, и галлюцинации',
    backBtn: 'Назад',
    intro: 'Сервис использует технологии генеративного искусственного интеллекта (ИИ) для создания опросов, викторин и различного контента. Участники полностью понимают и соглашаются со следующими условиями.',
    sections: [
      { title: '1. Характеристики технологии ИИ', content: ['① Результаты, созданные ИИ, производятся с использованием вероятностных технологий.', '② Ответы и контент, создаваемые ИИ, не всегда гарантируют точность, полноту, актуальность или пригодность.', '③ Даже на один и тот же вопрос могут быть получены разные результаты.'] },
      { title: '2. Явление галлюцинаций', content: ['• ИИ может генерировать информацию, отличную от реальных фактов, или несуществующую информацию.', '• Участники должны обязательно самостоятельно проверять результаты, созданные ИИ.'] },
      { title: '3. Ограничение профессиональных суждений', content: ['Результаты работы ИИ служат только справочным материалом и не должны использоваться в качестве единственного основания для:', '• Медицинских заключений', '• Юридических консультаций', '• Налоговых консультаций', '• Инвестиционных и финансовых решений', '• Заключения контрактов', '• Других вопросов, требующих профессионального суждения', 'При необходимости обязательно проконсультируйтесь со специалистами в соответствующей области.'] },
      { title: '4. Информация, вводимая в ИИ', content: ['Участники должны следить за тем, чтобы не вводить следующую информацию в поля ввода ИИ:', '• Номера удостоверений личности, паспортов, водительских прав', '• Финансовую информацию, пароли', '• Медицинскую информацию, конфиденциальные данные', '• Коммерческую тайну, личные данные третьих лиц', 'Ущерб, возникший в результате ввода такой информации, лежит исключительно на самом участнике.'] },
      { title: '5. Использование контента, созданного ИИ', content: ['① Вся ответственность за использование или распространение результатов, созданных ИИ, лежит на участнике.', '② Участники должны лично проверять, не нарушают ли результаты ИИ авторские права, товарные знаки, права на изображение, персональные данные или другие права третьих лиц.', '③ Юридический статус результатов ИИ может различаться в зависимости от конкретного случая в соответствии с применимым законодательством.'] },
      { title: '6. Ограничение ответственности', content: ['① Оператор не гарантирует точность, полноту, надежность, законность или пригодность результатов ИИ для определенной цели.', '② Оператор не несет ответственности за прямой или косвенный ущерб, понесенный участниками в результате использования результатов ИИ, за исключением случаев умысла или грубой небрежности.'] },
      { title: '7. Ограничение создания незаконного контента', content: ['Сервис может ограничивать или отказывать в создании следующего контента:', '• Контент, пропагандирующий незаконную деятельность, клевету, нарушение авторских прав', '• Контент, нарушающий неприкосновенность частной жизни, порнография, контент, разжигающий ненависть и дискриминацию', '• Создание вредоносного ПО, поддержка хакерства, контент, нарушающий действующее законодательство'] },
      { title: '8. Изменения в ИИ-сервисе', content: 'Оператор может изменять функции ИИ-сервиса или характеристики результатов в связи с изменениями модели ИИ, улучшением производительности или требованиями безопасности.' },
      { title: '9. Окончательная проверка', content: 'Участники должны окончательно рассмотреть результаты, созданные ИИ, и самостоятельно принять решение об их использовании; ответственность за использование их в качестве основы для важных решений лежит на самом участнике.' }
    ]
  },
  pt: {
    title: 'Consentimento de Isenção de Responsabilidade por Conteúdo Gerado por IA e Alucinações',
    backBtn: 'Voltar',
    intro: 'O serviço utiliza tecnologia de inteligência artificial (IA) gerativa para criar enquetes, quizzes e diversos conteúdos. Os membros compreendem integralmente e concordam com os seguintes termos.',
    sections: [
      { title: '1. Características da tecnologia de IA', content: ['① Os resultados gerados por IA são produzidos usando tecnologia baseada em probabilidades.', '② As respostas e conteúdos gerados por IA nem sempre garantem precisão, integridade, atualidade ou adequação.', '③ Resultados diferentes podem ser produzidos mesmo para a mesma pergunta.'] },
      { title: '2. Fenômeno de alucinação', content: ['• A IA pode gerar informações que diferem de fatos reais ou informações inexistentes.', '• Os membros devem verificar pessoalmente os resultados gerados pela IA.'] },
      { title: '3. Limitação de julgamento profissional', content: ['Os resultados gerados por IA são apenas para referência e não devem ser usados como base exclusiva para:', '• Julgamentos médicos', '• Aconselhamento jurídico', '• Aconselhamento fiscal', '• Decisões de investimento e financeiras', '• Conclusão de contratos', '• Outros assuntos que exijam julgamento profissional', 'Consulte especialistas na área correspondente, se necessário.'] },
      { title: '4. Informações de entrada de IA', content: ['Os membros devem tomar cuidado para não inserir as seguintes informações nos campos de entrada de IA:', '• Números de identidade, passaporte, carteira de motorista', '• Informações financeiras, senhas', '• Informações médicas, informações confidenciais', '• Segredos comerciais, informações pessoais de terceiros', 'Os danos decorrentes da inserção dessas informações são de responsabilidade exclusiva do membro.'] },
      { title: '5. Uso de conteúdo gerado por IA', content: ['① Toda a responsabilidade pelo uso ou distribuição dos resultados gerados por IA recae sobre o membro.', '② Os membros devem verificar diretamente se os resultados da IA infringem direitos autorais, marcas registradas, direitos de imagem, informações pessoais ou outros direitos de terceiros.', '③ As relações de direitos dos resultados da IA podem variar dependendo de cada caso, de acordo com as leis aplicáveis.'] },
      { title: '6. Limitação de responsabilidade', content: ['① O operador não garante a precisão, integridade, confiabilidade, legalidade ou adequação a um propósito específico dos resultados da IA.', '② O operador não será responsável por danos diretos ou indiretos sofridos pelos membros que utilizem os resultados da IA, exceto em caso de dolo ou culpa grave.'] },
      { title: '7. Restrição de geração de conteúdo ilegal', content: ['O serviço pode restringir ou recusar a geração de conteúdos como:', '• Conteúdo que promova atos ilegais, difamação, violação de direitos autorais', '• Conteúdo de violação de privacidade, pornografia, conteúdo de ódio e discriminatório', '• Criação de malware, suporte a hackers, conteúdo que viole as leis aplicables'] },
      { title: '8. Alterações no serviço de IA', content: 'O operador pode alterar as funções do serviço de IA ou as características dos resultados devido a mudanças no modelo de IA, melhorias de desempenho ou necessidades de segurança.' },
      { title: '9. Verificação final', content: 'Os membros devem revisar os resultados gerados pela IA e decidir de forma independente se devem utilizá-los; a responsabilidade de usá-los como base para decisões importantes recai sobre o próprio membro.' }
    ]
  },
  vi: {
    title: 'Đồng ý với Tuyên bố Miễn trừ Trách nhiệm về Nội dung do AI tạo ra và Hiện tượng Ảo giác',
    backBtn: 'Quay lại',
    intro: 'Dịch vụ này sử dụng công nghệ trí tuệ nhân tạo tạo sinh (AI) để tạo ra các cuộc khảo sát, câu đố và nội dung khác nhau. Thành viên hoàn toàn hiểu và đồng ý với các điều khoản sau.',
    sections: [
      { title: '1. Đặc điểm của công nghệ AI', content: ['① Kết quả do AI tạo ra được sản xuất bằng công nghệ dựa trên xác suất.', '② Các câu trả lời và nội dung do AI tạo ra không phải lúc nào cũng đảm bảo tính chính xác, đầy đủ, cập nhật hoặc phù hợp.', '③ Các kết quả khác nhau có thể được tạo ra ngay cả với cùng một câu hỏi.'] },
      { title: '2. Hiện tượng ảo giác', content: ['• AI có thể tạo ra thông tin khác với sự thật thực tế hoặc thông tin không tồn tại.', '• Thành viên phải trực tiếp xác minh các kết quả do AI tạo ra.'] },
      { title: '3. Hạn chế về phán đoán chuyên môn', content: ['Kết quả do AI tạo ra chỉ mang tính chất tham khảo và không được sử dụng làm cơ sở duy nhất cho:', '• Phán đoán y tế', '• Tư vấn pháp lý', '• Tư vấn thuế', '• Quyết định đầu tư và tài chính', '• Ký kết hợp đồng', '• Các vấn đề khác yêu cầu phán đoán chuyên môn', 'Vui lòng tham khảo ý kiến các chuyên gia trong lĩnh vực tương ứng nếu cần thiết.'] },
      { title: '4. Thông tin đầu vào của AI', content: ['Thành viên phải cẩn thận không nhập các thông tin sau vào ô nhập liệu AI:', '• Số căn cước, số hộ chiếu, số giấy phép lái xe', '• Thông tin tài chính, mật khẩu', '• Thông tin y tế, thông tin nhạy cảm', '• Bí mật thương mại, thông tin cá nhân của người khác', 'Thiệt hại phát sinh từ việc nhập các thông tin này hoàn toàn thuộc trách nhiệm của thành viên.'] },
      { title: '5. Sử dụng nội dung do AI tạo ra', content: ['① Mọi trách nhiệm khi sử dụng hoặc phân phối kết quả do AI tạo ra thuộc về thành viên.', '② Thành viên phải trực tiếp kiểm tra xem kết quả AI có vi phạm bản quyền, nhãn hiệu, quyền nhân thân, thông tin cá nhân hoặc các quyền khác của bên thứ ba hay không.', '③ Mối quan hệ quyền lợi đối với kết quả AI có thể thay đổi tùy theo từng trường hợp theo luật pháp có liên quan.'] },
      { title: '6. Giới hạn trách nhiệm', content: ['① Người vận hành không đảm bảo tính chính xác, đầy đủ, độ tin cậy, tính hợp pháp hoặc tính phù hợp cho một mục đích cụ thể của kết quả AI.', '② Người vận hành sẽ không chịu trách nhiệm đối với các thiệt hại trực tiếp hoặc gián tiếp do thành viên sử dụng kết quả AI gây ra, trừ khi có cố ý hoặc sơ suất lớn.'] },
      { title: '7. Hạn chế tạo nội dung bất hợp pháp', content: ['Dịch vụ có thể hạn chế hoặc từ chối tạo các nội dung như:', '• Nội dung cổ vũ hành vi phạm pháp, phỉ báng, vi phạm bản quyền', '• Nội dung vi phạm quyền riêng tư, văn hóa phẩm đồi trụy, nội dung thù hận và kỳ thị', '• Tạo mã độc, hỗ trợ hack, nội dung vi phạm pháp luật có liên quan'] },
      { title: '8. Thay đổi dịch vụ AI', content: 'Người vận hành có thể thay đổi các chức năng của dịch vụ AI hoặc đặc điểm của kết quả do thay đổi mô hình AI, cải thiện hiệu suất hoặc nhu cầu bảo mật.' },
      { title: '9. Kiểm tra lần cuối', content: 'Thành viên phải xem xét lại kết quả do AI tạo ra và tự quyết định xem có nên sử dụng hay không; trách nhiệm khi sử dụng làm cơ sở cho các quyết định quan trọng thuộc về chính thành viên.' }
    ]
  },
  th: {
    title: 'ความยินยอมคำประกาศปฏิเสธความรับผิดชอบเนื้อหาที่สร้างโดย AI และภาพหลอน (Hallucination)',
    backBtn: 'ย้อนกลับ',
    intro: 'บริการนี้ใช้เทคโนโลยีปัญญาประดิษฐ์เชิง générative (AI) เพื่อสร้างแบบสำรวจ แบบทดสอบ และเนื้อหาต่างๆ สมาชิกเข้าใจและยอมรับข้อกำหนดต่อไปนี้อย่าง 100%',
    sections: [
      { title: '1. ลักษณะของเทคโนโลยี AI', content: ['① ผลลัพธ์ที่สร้างโดย AI ถูกสร้างขึ้นโดยใช้เทคโนโลยีที่อิงตามความน่าจะเป็น', '② คำตอบและเนื้อหาที่สร้างโดย AI ไม่รับประกันความถูกต้อง ความสมบูรณ์ ความเป็นปัจจุบัน หรือความเหมาะสมเสมอไป', '③ ผลลัพธ์ที่แตกต่างกันอาจถูกสร้างขึ้นแม้จะเป็นคำถามเดียวกันก็ตาม'] },
      { title: '2. ปรากฏการณ์ภาพหลอน (Hallucination)', content: ['• AI อาจสร้างข้อมูลที่แตกต่างจากข้อเท็จจริงจริง หรือข้อมูลที่ไม่มีอยู่จริง', '• สมาชิกต้องตรวจสอบผลลัพธ์ที่สร้างโดย AI ด้วยตนเองเสมอ'] },
      { title: '3. ข้อจำกัดของการวินิจฉัยทางวิชาชีพ', content: ['ผลลัพธ์ที่สร้างโดย AI เป็นเพียงข้อมูลอ้างอิงเท่านั้น และห้ามใช้เป็นพื้นฐานเพียงอย่างเดียวสำหรับ:', '• การวินิจฉัยทางการแพทย์', '• คำปรึกษาทางกฎหมาย', '• คำปรึกษาด้านภาษี', '• การตัดสินใจลงทุนและการเงิน', '• การทำสัญญา', '• เรื่องอื่นๆ ที่ต้องอาศัยการวินิจฉัยระดับมืออาชีพ', 'โปรดปรึกษาผู้เชี่ยวชาญในสาขานั้นๆ หากจำเป็น'] },
      { title: '4. ข้อมูลป้อนเข้าของ AI', content: ['สมาชิกต้องระมัดระวังไม่ป้อนข้อมูลต่อไปนี้ลงในช่องป้อนข้อมูลของ AI:', '• หมายเลขบัตรประจำตัว, หมายเลขหนังสือเดินทาง, หมายเลขใบขับขี่', '• ข้อมูลทางการเงิน, รหัสผ่าน', '• ข้อมูลทางการแพทย์, ข้อมูลอ่อนไหว', '• ความลับทางการค้า, ข้อมูลส่วนบุคคลของผู้อื่น', 'ความเสียหายที่เกิดขึ้นจากการป้อนข้อมูลดังกล่าวถือเป็นความรับผิดชอบของสมาชิกเอง'] },
      { title: '5. การใช้ประโยชน์จากเนื้อหาที่สร้างโดย AI', content: ['① ความรับผิดชอบทั้งหมดในการใช้หรือเผยแพร่ผลลัพธ์ที่สร้างโดย AI เป็นของสมาชิก', '② สมาชิกต้องตรวจสอบโดยตรงว่าผลลัพธ์ของ AI ละเมิดลิขสิทธิ์ เครื่องหมายการค้า สิทธิ์ในภาพบุคคล ข้อมูลส่วนบุคคล หรือสิทธิ์อื่น ๆ ของบุคคลที่สามหรือไม่', '③ ความสัมพันธ์ด้านสิทธิ์ของผลลัพธ์ AI อาจแตกต่างกันไปตามแต่ละกรณีภายใต้กฎหมายที่เกี่ยวข้อง'] },
      { title: '6. ข้อจำกัดความรับผิดชอบ', content: ['① ผู้ดำเนินการไม่รับประกันความถูกต้อง ความสมบูรณ์ ความน่าเชื่อถือ ความชอบด้วยกฎหมาย หรือความเหมาะสมสำหรับวัตถุประสงค์เฉพาะของผลลัพธ์ AI', '② ผู้ดำเนินการจะไม่รับผิดชอบต่อความเสียหายทางตรงหรือทางอ้อมที่เกิดขึ้นกับสมาชิกจากการใช้ผลลัพธ์ AI ยกเว้นในกรณีที่มีเจตนาหรือความประมาทเลินเล่ออย่างร้ายแรง'] },
      { title: '7. การจำกัดการสร้างเนื้อหาผิดกฎหมาย', content: ['บริการอาจจำกัดหรือปฏิเสธการสร้างเนื้อหา เช่น:', '• เนื้อหาที่ส่งเสริมการกระทำผิดกฎหมาย การหมิ่นประมาท การละเมิดลิขสิทธิ์', '• เนื้อหาละเมิดความเป็นส่วนตัว ภาพอนาจาร เนื้อหาแสดงความเกลียดชังและการเลือกปฏิบัติ', '• การสร้างมัลแวร์ การสนับสนุนการแฮ็ก เนื้อหาที่ฝ่าฝืนกฎหมายที่เกี่ยวข้อง'] },
      { title: '8. การเปลี่ยนแปลงบริการ AI', content: 'ผู้ดำเนินการอาจเปลี่ยนแปลงฟังก์ชันของบริการ AI หรือลักษณะของผลลัพธ์เนื่องจากการเปลี่ยนแปลงโมเดล AI การปรับปรุงประสิทธิภาพ หรือความจำเป็นด้านความปลอดภัย' },
      { title: '9. การตรวจสอบขั้นสุดท้าย', content: 'สมาชิกต้องตรวจสอบผลลัพธ์ที่สร้างโดย AI เป็นครั้งสุดท้ายและตัดสินใจด้วยตนเองว่าจะใช้หรือไม่ ความรับผิดชอบในการใช้เป็นพื้นฐานสำหรับการตัดสินใจที่สำคัญตกเป็นของสมาชิกเอง' }
    ]
  },
  id: {
    title: 'Persetujuan Penafian Tanggung Jawab & Halusinasi Konten Buatan AI',
    backBtn: 'Kembali',
    intro: 'Layanan ini menggunakan teknologi kecerdasan buatan (AI) generatif untuk membuat survei, kuis, dan berbagai konten. Anggota sepenuhnya memahami dan menyetujui ketentuan berikut.',
    sections: [
      { title: '1. Karakteristik Teknologi AI', content: ['① Hasil buatan AI dihasilkan menggunakan teknologi berbasis probabilitas.', '② Jawaban dan konten yang dihasilkan oleh AI tidak selalu menjamin keakuratan, kelengkapan, kekinian, atau kesesuaian.', '③ Hasil yang berbeda dapat dihasilkan bahkan untuk pertanyaan yang sama.'] },
      { title: '2. Fenomena Halusinasi', content: ['• AI dapat menghasilkan informasi yang berbeda dari fakta sebenarnya atau informasi yang tidak ada.', '• Anggota harus selalu memverifikasi sendiri hasil buatan AI.'] },
      { title: '3. Pembatasan Penilaian Profesional', content: ['Hasil buatan AI hanya sebagai referensi dan tidak boleh digunakan sebagai satu-satunya dasar untuk:', '• Keputusan medis', '• Nasihat hukum', '• Konsultasi pajak', '• Keputusan investasi dan keuangan', '• Penandatanganan kontrak', '• Hal lain yang memerlukan penilaian profesional', 'Silakan berkonsultasi dengan ahli di bidang terkait jika diperlukan.'] },
      { title: '4. Informasi Masukan AI', content: ['Anggota harus berhati-hati untuk tidak memasukkan informasi berikut ke dalam kolom masukan AI:', '• Nomor identitas, nomor paspor, nomor surat izin mengemudi', '• Informasi keuangan, kata sandi', '• Informasi medis, informasi sensitif', '• Rahasia dagang, informasi pribadi pihak lain', 'Kerugian yang timbul akibat memasukkan informasi tersebut sepenuhnya menjadi tanggung jawab anggota.'] },
      { title: '5. Pemanfaatan Konten Buatan AI', content: ['① Segala tanggung jawab atas penggunaan atau pendistribusian hasil buatan AI berada pada anggota.', '② Anggota harus memeriksa secara langsung apakah hasil AI melanggar hak cipta, merek dagang, hak potret, informasi pribadi, atau hak lain pihak ketiga.', '③ Hubungan hak atas hasil AI dapat bervariasi tergantung pada kasus masing-masing sesuai hukum yang berlaku.'] },
      { title: '6. Batasan Tanggung Jawab', content: ['① Operator tidak menjamin keakuratan, kelengkapan, keandalan, legalitas, atau kesesuaian hasil AI untuk tujuan tertentu.', '② Operator tidak bertanggung jawab atas kerugian langsung atau tidak langsung yang dialami anggota karena menggunakan hasil AI, kecuali karena kesengajaan atau kelalaian besar.'] },
      { title: '7. Pembatasan Pembuatan Konten Ilegal', content: ['Layanan dapat membatasi atau menolak pembuatan konten seperti:', '• Konten yang mendorong tindakan ilegal, pencemaran nama baik, pelanggaran hak cipta', '• Konten pelanggaran privasi, pornografi, konten kebencian dan diskriminasi', '• Pembuatan malware, dukungan peretasan, konten yang melanggar hukum yang berlaku'] },
      { title: '8. Perubahan Layanan AI', content: 'Operator dapat mengubah fungsi layanan AI atau karakteristik hasil karena perubahan model AI, peningkatan kinerja, atau kebutuhan keamanan.' },
      { title: '9. Verifikasi Akhir', content: 'Anggota harus meninjau hasil buatan AI secara akhir dan memutuskan sendiri apakah akan menggunakannya; tanggung jawab untuk menggunakannya sebagai dasar keputusan penting berada pada anggota itu sendiri.' }
    ]
  },
  ar: {
    title: 'الموافقة على إخلاء المسؤولية عن المحتوى المُولّد بواسطة الذكاء الاصطناعي والهلوسة',
    backBtn: 'رجوع',
    intro: 'تستخدم الخدمة تقنية الذكاء الاصطناعي التوليدي لإنشاء استطلاعات الرأي والاختبارات والمحتويات المختلفة. يفهم الأعضاء الشروط التالية تماماً ويوافقون عليها.',
    sections: [
      { title: '1. خصائص تقنية الذكاء الاصطناعي', content: ['① يتم إنتاج نتائج الذكاء الاصطناعي باستخدام تكنولوجيا قائمة على الاحتمالات.', '② الإجابات والمحتويات التي يولدها الذكاء الاصطناعي لا تضمن دائمًا الدقة، أو الاكتمال، أو الحداثة، أو الملاءمة.', '③ قد يتم إنتاج نتائج مختلفة حتى لنفس السؤال.'] },
      { title: '2. ظاهرة الهلوسة', content: ['• يمكن للذكاء الاصطناعي توليد معلومات تختلف عن الحقائق الفعليّة أو معلومات غير موجودة.', '• يجب على الأعضاء التحقق من نتائج الذكاء الاصطناعي بأنفسهم بشكل مباشر.'] },
      { title: '3. قيود التقييم المهني', content: ['نتائج الذكاء الاصطناعي هي للإشارة فقط ولا يجوز استخدامها الأساس الوحيد لـ:', '• القرارات الطبية', '• الاستشارات القانونية', '• الاستشارات الضريبية', '• قرارات الاستثمار والتمويل', '• إبرام العقود', '• الأمور الأخرى التي تتطلب تقييماً مهنياً', 'يرجى استشارة الخبراء في المجال المعني إذا لزم الأمر.'] },
      { title: '4. معلومات إدخال الذكاء الاصطناعي', content: ['يجب على الأعضاء توخي الحذر وعدم إدخال المعلومات التالية في حقول إدخال الذكاء الاصطناعي:', '• أرقام الهويات، أرقام جوازات السفر، أرقام رخص القيادة', '• المعلومات المالية، كلمات المرور', '• المعلومات الطبية، المعلومات الحساسة', '• الأسرار التجارية، المعلومات الشخصية للآخرين', 'الأضرار الناشئة عن إدخال هذه المعلومات تقع على مسؤولية العضو وحده.'] },
      { title: '5. الاستفادة من المحتوى المُولّد بالذكاء الاصطناعي', content: ['① تقع كامل المسؤولية عن استخدام أو توزیع نتائج الذكاء الاصطناعي على عاتق العضو.', '② يجب على الأعضاء التحقق مباشرة مما إذا كانت نتائج الذكاء الاصطناعي تنتهك حقوق الطبع والنشر، أو العلامات التجارية، أو حقوق الصورة، أو البيانات الشخصية، أو الحقوق الأخرى لطراف ثالث.', '③ قد تختلف علاقات الحقوق الخاصة بنتائج الذكاء الاصطناعي حسب كل حالة وفقًا للقوانين المعمول بها.'] },
      { title: '6. تحديد المسؤولية', content: ['① لا يضمن المشغل دقة أو اكتمال أو موثوقية أو قانونية أو ملاءمة نتائج الذكاء الاصطناعي لغرض معين.', '② لا يتحمل المشغل المسؤولية عن الأضرار المباشرة أو غير المباشرة التي يتكبدها الأعضاء جراء استخدام نتائج الذكاء الاصطناعي، إلا في حالة العمد أو الإهمال الجسيم.'] },
      { title: '7. تقييد إنشاء المحتوى غير القانوني', content: ['يجوز للخدمة تقييد أو رفض إنشاء محتوى مثل:', '• المحتوى الذي يحرض على أعمال غير قانونية، التشهير، انتهاك حقوق الطبع والنشر', '• محتوى انتهاك الخصوصية، المواد الإباحية، محتوى الكراهية والتمييز', '• إنتاج البرمجيات الخبيثة، دعم القرصنة، المحتوى المخالف للقوانين ذات الصلة'] },
      { title: '8. تغييرات خدمة الذكاء الاصطناعي', content: 'يجوز للمشغل تغيير وظائف خدمة الذكاء الاصطناعي أو خصائص النتائج بسبب تغييرات نموذج الذكاء الاصطناعي، أو تحسين الأداء، أو المتطلبات الأمنية.' },
      { title: '9. التحقق النهائي', content: 'يجب على الأعضاء مراجعة نتائج الذكاء الاصطناعي نهائياً وتحديد ما إذا كان سيتم استخدامها بأنفسهم؛ وتقع مسؤولية استخدامها كأساس لقرارات هامة على العضو نفسه.' }
    ]
  },
  hi: {
    title: 'एआई जनित सामग्री की जिम्मेदारी और मतिभ्रम (हलूचिनेशन) अस्वीकरण सहमति',
    backBtn: 'वापस जाएं',
    intro: 'यह सेवा सर्वेक्षण, क्विज़ और विभिन्न सामग्री उत्पन्न करने के लिए जनरेटिव आर्टिफिशियल इंटेलिजेंस (एआई) तकनीक का उपयोग करती है। सदस्य निम्नलिखित शर्तों को पूरी तरह समझते हैं और उनसे सहमत हैं।',
    sections: [
      { title: '1. एआई तकनीक की विशेषताएं', content: ['① एआई-जनित परिणाम संभाव्यता-आधारित तकनीक का उपयोग करके उत्पन्न किए जाते हैं।', '② एआई द्वारा उत्पन्न उत्तर और सामग्री हमेशा सटीकता, पूर्णता, नवीनता या उपयुक्तता की गारंटी नहीं देते हैं।', '③ एक ही प्रश्न के लिए भी अलग-अलग परिणाम उत्पन्न हो सकते हैं।'] },
      { title: '2. मतिभ्रम (हलूचिनेशन) घटना', content: ['• एआई वास्तविक तथ्यों से भिन्न जानकारी या ऐसी जानकारी उत्पन्न कर सकता है जो मौजूद नहीं है।', '• सदस्यों को एआई-जनित परिणामों की स्वयं सीधे जांच अवश्य करनी चाहिए।'] },
      { title: '3. पेशेवर निर्णय की सीमा', content: ['एआई-जनित परिणाम केवल संदर्भ के लिए हैं और इन्हें निम्नलिखित का एकमात्र आधार नहीं बनाया जाना चाहिए:', '• चिकित्सा निर्णय', '• कानूनी सलाह', '• कर परामर्श', '• निवेश और वित्तीय निर्णय', '• अनुबंध निष्कर्ष', '• अन्य मामले जिनके लिए पेशेवर निर्णय की आवश्यकता होती है', 'यदि आवश्यक हो तो कृपया संबंधित क्षेत्र के विशेषज्ञों से परामर्श लें।'] },
      { title: '4. एआई इनपुट जानकारी', content: ['सदस्यों को एआई इनपुट फ़ील्ड में निम्नलिखित जानकारी दर्ज करने से सावधान रहना चाहिए:', '• पहचान संख्या, पासपोर्ट नंबर, ड्राइवर का लाइसेंस नंबर', '• वित्तीय जानकारी, पासवर्ड', '• चिकित्सा जानकारी, संवेदनशील जानकारी', '• व्यावसायिक रहस्य, दूसरों की व्यक्तिगत जानकारी', 'ऐसी जानकारी दर्ज करने से उत्पन्न होने वाला नुकसान पूरी तरह से सदस्य की अपनी जिम्मेदारी है।'] },
      { title: '5. एआई-जनित सामग्री का उपयोग', content: ['① एआई-जनित परिणामों का उपयोग या वितरण करने की सारी जिम्मेदारी सदस्य की है।', '② सदस्यों को सीधे यह जांचना चाहिए कि क्या एआई परिणाम तीसरे पक्ष के कॉपीराइट, ट्रेडमार्क, पोर्ट्रेट अधिकारों, व्यक्तिगत जानकारी या अन्य अधिकारों का उल्लंघन करते हैं।', '③ लागू कॉपीराइट कानूनों के अनुसार व्यक्तिगत मामलों के आधार पर एआई परिणामों के अधिकार संबंध अलग-अलग हो सकते हैं।'] },
      { title: '6. दायित्व की सीमा', content: ['① ऑपरेटर एआई परिणामों की सटीकता, पूर्णता, विश्वसनीयता, वैधता या किसी विशेष उद्देश्य के लिए उपयुक्तता की गारंटी नहीं देता है।', '② ऑपरेटर जानबूझकर या घोर लापरवाही को छोड़कर, एआई परिणामों का उपयोग करके सदस्यों को होने वाले प्रत्यक्ष या अप्रत्यक्ष नुकसान के लिए उत्तरदायी नहीं होगा।'] },
      { title: '7. अवैध सामग्री निर्माण प्रतिबंध', content: ['सेवा निम्नलिखित सामग्री के निर्माण को प्रतिबंधित या अस्वीकार कर सकती है:', '• अवैध कृत्यों को बढ़ावा देने वाली सामग्री, मानहानि, कॉपीराइट उल्लंघन', '• गोपनीयता का उल्लंघन करने वाली सामग्री, अछूत/अशोभनीय सामग्री, घृणा और भेदभावपूर्ण सामग्री', '• मालवेयर निर्माण, हैकिंग सहायता सामग्री, संबंधित कानूनों का उल्लंघन करने वाली सामग्री'] },
      { title: '8. एआई सेवा में परिवर्तन', content: 'ऑपरेटर एआई मॉडल परिवर्तनों, प्रदर्शन में सुधार या सुरक्षा आवश्यकताओं के कारण एआई सेवा के कार्यों या परिणामों की विशेषताओं को बदल सकता है।' },
      { title: '9. अंतिम सत्यापन', content: 'सदस्यों को एआई-जनित परिणामों की अंतिम रूप से समीक्षा करनी चाहिए और खुद तय करना चाहिए कि उनका उपयोग करना है या नहीं; महत्वपूर्ण निर्णयों के आधार के रूप में उनका उपयोग करने पर जिम्मेदारी सदस्य की ही होती है।' }
    ]
  },
  it: {
    title: 'Consenso alla limitazione di responsabilità e allucinazione per contenuti generati dall’IA',
    backBtn: 'Indietro',
    intro: 'Il servizio utilizza la tecnologia dell’intelligenza artificiale (IA) generativa per creare sondaggi, quiz e vari contenuti. I membri comprendono appieno e accettano i seguenti termini.',
    sections: [
      { title: '1. Caratteristiche della tecnologia IA', content: ['① I risultati generati dall’IA sono prodotti utilizzando una tecnologia basata sulle probabilità.', '② Le risposte e i contenuti generati dall’IA non garantiscono sempre accuratezza, completezza, tempestività o idoneità.', '③ È possibile ottenere risultati diversi anche per la stessa domanda.'] },
      { title: '2. Fenomeno di allucinazione', content: ['• L’IA può generare informazioni diverse dai fatti reali o informazioni inesistenti.', '• I membri devono verificare personalmente e direttamente i risultati generati dall’IA.'] },
      { title: '3. Limitazione del giudizio professionale', content: ['I risultati generati dall’IA sono solo di riferimento e non devono essere utilizzati come unico fondamento per:', '• Decisioni mediche', '• Consulenza legale', '• Consulenza fiscale', '• Decisioni di investimento e finanziarie', '• Conclusione di contratti', '• Altre questioni che richiedono un giudizio professionale', 'Si prega di consultare esperti nel rispettivo campo se necessario.'] },
      { title: '4. Informazioni immesse nell’IA', content: ['I membri devono prestare attenzione a non inserire le seguenti informazioni nei campi di input dell’IA:', '• Numeri di identificazione, passaporto, patente di guida', '• Informazioni finanziarie, password', '• Informazioni mediche, informazioni sensibili', '• Segreti commerciali, dati personali di terzi', 'I danni derivanti dall’inserimento di tali informazioni sono di esclusiva responsabilità del membro.'] },
      { title: '5. Utilizzo dei contenuti generati dall’IA', content: ['① La piena responsabilità per l’utilizzo o la distribuzione dei risultati generati dall’IA spetta al membro.', '② I membri devono verificare direttamente se i risultati dell’IA violano diritti d’autore, marchi, diritti d’immagine, informazioni personali o altri diritti di terzi.', '③ I rapporti di diritti relativi ai risultati dell’IA possono variare a seconda dei singoli casi in base alle leggi vigenti.'] },
      { title: '6. Limitazione di responsabilità', content: ['① L’operatore non garantisce l’accuratezza, la completezza, l’affidabilità, la legalità o l’idoneità a uno scopo particolare dei risultati dell’IA.', '② L’operatore non sarà responsabile per danni diretti o indiretti subiti dai membri che utilizzano i risultati dell’IA, salvo in caso di dolo o colpa grave.'] },
      { title: '7. Restrizione sulla generazione di contenuti illegali', content: ['Il servizio può limitare o rifiutare la generazione di contenuti quali:', '• Contenuti che incoraggiano atti illegali, diffamazione, violazione del copyright', '• Contenuti che violano la privacy, pornografia, contenuti di odio e discriminatori', '• Creazione di malware, supporto all’hacking, contenuti che violano le leggi vigenti'] },
      { title: '8. Modifiche al servizio IA', content: 'L’operatore può modificare le funzioni del servizio IA o le caratteristiche dei risultati a causa di modifiche del modello IA, miglioramenti delle prestazioni o esigenze di sicurezza.' },
      { title: '9. Verifica finale', content: 'I membri devono esaminare i risultati generati dall’IA e decidere autonomamente se utilizzarli; la responsabilità derivante dall’uso degli stessi come base per decisioni importanti spetta al membro stesso.' }
    ]
  },
  tr: {
    title: 'Yapay Zeka Tarafından Üretilen İçerik Sorumluluğu ve Halüsinasyon Sorumluluk Reddi Onayı',
    backBtn: 'Geri Dön',
    intro: 'Hizmet, anketler, sınavlar ve çeşitli içerikler oluşturmak için üretken yapay zeka (YZ) teknolojisini kullanır. Üyeler aşağıdaki şartları tamamen anlar ve kabul eder.',
    sections: [
      { title: '1. Yapay Zeka Teknolojisinin Özellikleri', content: ['① YZ tarafından üretilen sonuçlar olasılığa dayalı teknoloji kullanılarak üretilir.', '② YZ tarafından oluşturulan yanıtlar ve içerikler her zaman doğruluk, eksiksizlik, güncellik veya uygunluk garanti etmez.', '③ Aynı soru için bile farklı sonuçlar üretilebilir.'] },
      { title: '2. Halüsinasyon Fenomeni', content: ['• YZ, gerçek olgulardan farklı bilgiler veya var olmayan bilgiler üretebilir.', '• Üyeler YZ tarafından üretilen sonuçları bizzat kontrol etmek zorundadır.'] },
      { title: '3. Profesyonel Yargının Sınırlandırılması', content: ['YZ üretim sonuçları yalnızca referans amaçlıdır ve aşağıdakiler için tek dayanak olarak kullanılmamalıdır:', '• Tıbbi kararlar', '• Hukuki danışmanlık', '• Vergi danışmanlığı', '• Yatırım ve finansal kararlar', '• Sözleşme akdi', '• Profesyonel yargı gerektiren diğer hususlar', 'Gerekirse lütfen ilgili alandaki uzmanlara danışın.'] },
      { title: '4. YZ Giriş Bilgileri', content: ['Üyeler, YZ giriş alanlarına şu bilgileri girmemeye özen göstermelidir:', '• Kimlik numaraları, pasaport numaraları, ehliyet numaraları', '• Finansal bilgiler, şifreler', '• Tıbbi bilgiler, hassas bilgiler', '• Ticari sırlar, başkalarının kişisel bilgileri', 'Bu bilgilerin girilmesinden doğacak zararlar tamamen üyenin kendi sorumluluğundadır.'] },
      { title: '5. YZ Tarafından Üretilen İçeriğin Kullanımı', content: ['① YZ üretim sonuçlarını kullanma veya dağıtma sorumluluğu tamamen üyeye aittir.', '② Üyeler, YZ sonuçlarının üçüncü şahısların telif haklarını, ticari markalarını, kişilik haklarını, kişisel bilgilerini veya diğer haklarını ihlal edip etmediğini doğrudan kontrol etmelidir.', '③ İlgili telif hakkı yasalarına göre YZ sonuçlarının hak ilişkileri her bir duruma göre değişiklik gösterebilir.'] },
      { title: '6. Sorumluluğun Sınırlandırılması', content: ['① İşletmeci, YZ sonuçlarının doğruluğunu, eksiksizliğini, güvenilirliğini, yasallığını veya belirli bir amaca uygunluğunu garanti etmez.', '② İşletmeci, üyelerin YZ sonuçlarını kullanmasından kaynaklanan doğrudan veya dolaylı zararlardan kast veya ağır kusur olmadıkça sorumlu tutulamaz.'] },
      { title: '7. Yasadışı İçerik Üretim Kısıtlaması', content: ['Hizmet şu tür içeriklerin üretilmesini kısıtlayabilir veya reddedebilir:', '• Yasadışı eylemleri teşvik eden içerikler, iftira, telif hakkı ihlali', '• Gizlilik ihlali, pornografi, nefret ve ayrımcılık içeren içerikler', '• Kötü amaçlı yazılım oluşturma, hackleme desteği, ilgili yasalara aykırı içerikler'] },
      { title: '8. YZ Hizmet Değişiklikleri', content: 'İşletmeci, YZ model değişiklikleri, performans iyileştirmeleri veya güvenlik gereksinimleri nedeniyle YZ hizmetinin işlevlerini veya sonuçların özelliklerini değiştirebilir.' },
      { title: '9. Son Onay', content: 'Üyeler YZ üretim sonuçlarını nihai olarak gözden geçirmeli ve bunları kullanıp kullanmayacağına kendi karar vermelidir; önemli kararlar için temel olarak kullanılmasından doğan sorumluluk üyeye aittir.' }
    ]
  },
  nl: {
    title: 'Toestemming AI-gegenereerde inhoud aansprakelijkheid & hallucinatie disclaimer',
    backBtn: 'Terug',
    intro: 'De dienst maakt gebruik van generatieve kunstmatige intelligentie (AI) technologie om enquêtes, quizzen en verschillende inhoud te genereren. Leden begrijpen de volgende voorwaarden volledig en gaan hiermee akkoord.',
    sections: [
      { title: '1. Kenmerken van AI-technologie', content: ['① Door AI gegenereerde resultaten worden geproduceerd met behulp van op waarschijnlijkheid gebaseerde technologie.', '② Door AI gegenereerde antwoorden en inhoud garanderen niet altijd nauwkeurigheid, volledigheid, aktuelliteit of geschiktheid.', '③ Zelfs voor dezelfde vraag kunnen verschillende resultaten worden gegenereerd.'] },
      { title: '2. Hallucinatieverschijnsel', content: ['• AI kan informatie genereren die afwijkt van feitelijke gebeurtenissen of niet-bestaande informatie.', '• Leden moeten door AI gegenereerde resultaten altijd zelf direct controleren.'] },
      { title: '3. Beperking van professioneel oordeel', content: ['Door AI gegenereerde resultaten dienen alleen als referentie en mogen niet worden gebruikt als enige basis voor:', '• Medische beslissingen', '• Juridisch advies', '• Fiscale advisering', '• Investerings- en financiële beslissingen', '• Contractsluiting', '• Andere zaken die een professioneel oordeel vereisen', 'Raadpleeg indien nodig altijd experts op het desbetreffende vakgebied.'] },
      { title: '4. AI-invoerinformatie', content: ['Leden moeten opletten dat ze de volgende informatie niet invoeren in AI-invoervelden:', '• Burgerservicenummers, paspoortnummers, rijbewijsnummers', '• Financiële informatie, wachtwoorden', '• Medische informatie, gevoelige informatie', '• Bedrijfsgeheimen, persoonsgegevens van anderen', 'Schade die voortvloeit uit het invoeren hiervan is uitsluitend de verantwoordelijkheid van het lid zelf.'] },
      { title: '5. Gebruik van AI-gegenereerde inhoud', content: ['① Alle verantwoordelijkheid voor het gebruik of de verspreiding van door AI gegenereerde resultaten ligt bij het lid.', '② Leden moeten direct controleren of AI-resultaten inbreuk maken op auteursrechten, merkrechten, portretrechten, persoonsgegevens of andere rechten van derden.', '③ De rechtsbetrekkingen van AI-resultaten kunnen per afzonderlijk geval verschillen op grond van de toepasselijke wetgeving.'] },
      { title: '6. Beperking van aansprakelijkheid', content: ['① De exploitant garandeert niet de nauwkeurigheid, volledigheid, betrouwbaarheid, rechtmatigheid of geschiktheid voor een bepaald doel van AI-resultaten.', '② De exploitant is niet aansprakelijk voor directe of indirecte schade opgelopen door leden die AI-resultaten gebruiken, tenzij er sprake is van opzet of grove nalatigheid.'] },
      { title: '7. Beperking van illegale inhoud', content: ['De dienst kan het genereren van de volgende inhoud beperken of weigeren:', '• Inhoud die illegale handelingen stimuleert, laster, inbreuk op auteursrechten', '• Schending van privacy, pornografie, haatdragende en discriminatorische inhoud', '• Creatie van malware, ondersteuning van hacking, inhoud in strijd met relevante wetgeving'] },
      { title: '8. Wijzigingen in de AI-dienst', content: 'De exploitant kan de functies van de AI-dienst of de kenmerken van de resultaten wijzigen als gevolg van AI-modelwijzigingen, prestatieverbeteringen of beveiligingsbehoeften.' },
      { title: '9. Definitieve controle', content: 'Leden moeten door AI gegenereerde resultaten definitief beoordelen en zelf beslissen of ze deze gebruiken; de verantwoordelijkheid bij gebruik als basis voor belangrijke beslissingen ligt bij het lid zelf.' }
    ]
  },
  pl: {
    title: 'Zgoda na wyłączenie odpowiedzialności za treści generowane przez AI i halucynacje',
    backBtn: 'Wróć',
    intro: 'Usługa wykorzystuje technologię generatywnej sztucznej inteligencji (AI) do tworzenia ankiet, quizów i różnorodnych treści. Członkowie w pełni rozumieją i akceptują poniższe warunki.',
    sections: [
      { title: '1. Cechy technologii AI', content: ['① Wyniki generowane przez AI są tworzone przy użyciu technologii opartej na prawdopodobieństwie.', '② Odpowiedzi i treści generowane przez AI nie zawsze gwarantują dokładność, kompletność, aktualność ani przydatność.', '③ Różne wyniki mogą być generowane nawet dla tego samego pytania.'] },
      { title: '2. Zjawisko halucynacji', content: ['• AI może generować informacje odbiegające od rzeczywistych faktów lub informacje nieistniejące.', '• Członkowie muszą koniecznie osobiście weryfikować wyniki generowane przez AI.'] },
      { title: '3. Ograniczenie profesjonalnej oceny', content: ['Wyniki generowane przez AI służą wyłącznie jako materiał pomocniczy i nie powinny być używane jako jedyna podstawa do:', '• Decyzji medycznych', '• Porad prawnych', '• Doradztwa podatkowego', '• Decyzji inwestycyjnych i finansowych', '• Zawierania umów', '• Innych spraw wymagających profesjonalnej oceny', 'W razie potrzeby należy skonsultować się z ekspertami w danej dziedzinie.'] },
      { title: '4. Informacje wprowadzane do AI', content: ['Członkowie powinni uważać, aby nie wpisywać następujących informacji w polach wprowadzania AI:', '• Numerów PESEL, numerów paszportów, numerów praw jazdy', '• Informacji finansowych, haseł', '• Informacji medycznych, danych wrażliwych', '• Tajemnic handlowych, danych osobowych innych osób', 'Szkody wynikające z wprowadzenia takich danych obciążają wyłącznie samego członka.'] },
      { title: '5. Wykorzystanie treści generowanych przez AI', content: ['① Całkowita odpowiedzialność za wykorzystanie lub dystrybucję wyników generowanych przez AI spoczywa na członku.', '② Członkowie muszą bezpośrednio sprawdzać, czy wyniki AI nie naruszają praw autorskich, znaków towarowych, praw do wizerunku, danych osobowych lub innych praw osób trzecich.', '③ Kwestie prawne dotyczące wyników AI mogą się różnić w zależności od indywidualnego przypadku zgodnie z obowiązującymi przepisami prawa.'] },
      { title: '6. Ograniczenie odpowiedzialności', content: ['① Operator nie gwarantuje dokładności, kompletności, niezawodności, legalności ani przydatności wyników AI do określonego celu.', '② Operator nie ponosi odpowiedzialności za bezpośrednie lub pośrednie szkody poniesione przez członków korzystających z wyników AI, chyba że wynikają one z winy umyślnej lub rażącego niedbalstwa.'] },
      { title: '7. Ograniczenie generowania nielegalnych treści', content: ['Usługa może ograniczać lub odmawiać generowania treści takich jak:', '• Treści promujące działania nielegalne, zniesławienie, naruszenie praw autorskich', '• Naruszenie prywatności, pornografię, treści nawołujące do nienawiści i dyskryminacyjne', '• Tworzenie złośliwego oprogramowania, wspieranie hakowania, treści naruszające powiązane przepisy'] },
      { title: '8. Zmiany w usłudze AI', content: 'Operator może zmieniać funkcje usługi AI lub cechy wyników ze względu na zmiany modelu AI, poprawę wydajności lub wymogi bezpieczeństwa.' },
      { title: '9. Ostateczna weryfikacja', content: 'Członkowie muszą ostatecznie przejrzeć wyniki generowane przez AI i samodzielnie zdecydować o ich wykorzystaniu; odpowiedzialność za użycie ich jako podstawy do ważnych decyzji spoczywa na samym członku.' }
    ]
  },
  sv: {
    title: 'Samtycke till ansvarsfriskrivning för AI-genererat innehåll och hallucinationer',
    backBtn: 'Tillbaka',
    intro: 'Tjänsten använder generativ artificifikell intelligens (AI) för att skapa enkäter, frågesporter och diverse innehåll. Medlemmarna förstår till fullo och godkänner följande villkor.',
    sections: [
      { title: '1. Egenskaper hos AI-teknik', content: ['① AI-genererade resultat produceras med hjälp av sannolikhetsbaserad teknik.', '② Svar och innehåll som genereras av AI garanterar inte alltid noggrannhet, fullständighet, aktualitet eller lämplighet.', '③ Olika resultat kan genereras även för samma fråga.'] },
      { title: '2. Hallucinationsfenomen', content: ['• AI kan generera information som skiljer sig från faktiska fakta eller information som inte existerar.', '• Medlemmar måste alltid kontrollera AI-genererade resultat direkt på egen hand.'] },
      { title: '3. Begränsning av professionellt omdöme', content: ['AI-genererade resultat är endast referensmaterial och får inte användas som enda grund för:', '• Medicinska bedömningar', '• Juridisk rådgivning', '• Skatterådgivning', '• Investerings- och finansbeslut', '• Ingående av kontrakt', '• Andra frågor som kräver professionellt omdöme', 'Rådfråga experter inom respektive område vid behov.'] },
      { title: '4. AI-inmatningsinformation', content: ['Medlemmar måste vara försiktiga så att de inte matar in följande information i AI-inmatningsfält:', '• Personnummer, passnummer, körkortsnummer', '• Finansiell information, lösenord', '• Medicinsk information, känslig information', '• Affärshemligheter, andra personers personuppgifter', 'Skador som uppstår till följd av inmatning av sådan information är helt medlemmens eget ansvar.'] },
      { title: '5. Användning av AI-genererat innehåll', content: ['① Allt ansvar för att använda eller distribuera AI-genererade resultat ligger hos medlemmen.', '② Medlemmar måste direkt kontrollera om AI-resultat gör intrång i tredje parts upphovsrätt, varumärkesrätt, porträtträtt, personuppgifter eller andra rättigheter.', '③ Rättighetsförhållanden för AI-resultat kan variera beroende på enskilda fall i enlighet med tillämpliga lagar.'] },
      { title: '6. Ansvarsbegränsning', content: ['① Operatören garanterar inte noggrannheten, fullständigheten, tillförlitligheten, lagligheten eller lämpligheten för ett visst syfte av AI-resultaten.', '② Operatören ansvarar inte för direkt eller indirekt skada som drabbas av medlemmar som använder AI-resultat, såvida det inte rör sig om uppsåt eller grov vårdslöshet.'] },
      { title: '7. Begränsning av olagligt innehåll', content: ['Tjänsten kan begränsa eller vägra generering av innehåll såsom:', '• Innehåll som uppmuntrar till olagliga handlingar, förtal, upphovsrättsintrång', '• Integritetsintrång, pornografi, hatpropaganda och diskriminerande innehåll', '• Skapande av skadlig kod, hackingstöd, innehåll som bryter mot gällande lagar'] },
      { title: '8. Ändringar i AI-tjänsten', content: 'Operatören kan ändra AI-tjänstens funktioner eller resultatens egenskaper på grund av AI-modelländringar, prestandaförbättringar eller säkerhetskrav.' },
      { title: '9. Slutlig verifiering', content: 'Medlemmar måste slutligen granska AI-genererade resultat och själva avgöra om de ska användas; ansvaret för att använda dem som grund för viktiga beslut vilar på medlemmen själv.' }
    ]
  },
  fi: {
    title: 'Suostumus tekoälyn tuottaman sisällön vastuuvapauslausekkeeseen ja harhoihin',
    backBtn: 'Takaisin',
    intro: 'Palvelu käyttää generatiivista tekoälytekniikkaa (AI) kyselyiden, visojen ja erilaisen sisällön luomiseen. Jäsenet ymmärtävät täysin ja hyväksyvät seuraavat ehdot.',
    sections: [
      { title: '1. Tekoälytekniikan ominaisuudet', content: ['① Tekoälyn tuottamat tulokset luodaan todennäköisyyspohjaisen tekniikan avulla.', '② Tekoälyn luomat vastaukset ja sisältö eivät aina takaa tarkkuutta, täydellisyyttä, ajantasaisuutta tai sopivuutta.', '③ Erilaisia tuloksia voidaan tuottaa jopa samaan kysymykseen.'] },
      { title: '2. Harha-ilmiö (Hallucination)', content: ['• Tekoäly voi luoda tietoa, joka poikkeaa todellisista tosiasioista tai on olemematonta tietoa.', '• Jäsenten on ehdottomasti tarkistettava tekoälyn tuottamat tulokset henkilökohtaisesti.'] },
      { title: '3. Ammatillisen arvioinnin rajoitukset', content: ['Tekoälyn tuottamat tulokset ovat vain viitemateriaalia, eikä niitä saa käyttää ainoana perustana seuraaville:', '• Lääketieteelliset päätökset', '• Oikeudellinen neuvonta', '• Veronneuvonta', '• Sijoitus- ja rahoituspäätökset', '• Sopimusten solmiminen', '• Muut asiat, jotka vaativat ammatillista harkintaa', 'Käänny tarvittaessa asianomaisen alan asiantuntijoiden puoleen.'] },
      { title: '4. Tekoälyn syöttötiedot', content: ['Jäsenten on varottava syöttämästä seuraavia tietoja tekoälyn syöttökenttiin:', '• Henkilötunnukset, passinumerot, ajokorttinumerot', '• Taloustiedot, salasanat', '• Lääketieteelliset tiedot, arkaluonteiset tiedot', '• Liikesalaisuudet, muiden henkilötietoja', 'Tollaisten tietojen syöttämisestä aiheutuvat vahingot ovat yksinomaan jäsenen omalla vastuulla.'] },
      { title: '5. Tekoälyn tuottaman sisällön hyödyntäminen', content: ['① Vastuu tekoälyn tuottamien tulosten hyödyntämisestä tai levittämisestä on kokonaan jäsenellä.', '② Jäsenten on suoraan tarkistettava, loukkaavatko tekoälyn tulokset kolmansien osapuolten tekijänoikeuksia, tavaramerkkejä, muotokuvausoikeuksia, henkilötietoja tai muita oikeuksia.', '③ Tekoälytulosten oikeudelliset suhteet voivat vaihdella tapauskohtaisesti sovellettavien lakien mukaisesti.'] },
      { title: '6. Vastuun rajoitus', content: ['① Operaattori ei takaa tekoälytulosten tarkkuutta, täydellisyyttä, luotettavuutta, laillisuutta tai soveltuvuutta tiettyyn tarkoitukseen.', '② Operaattori ei ole vastuussa suorista tai epäsuorista vahingoista, joita jäsenille aiheutuu tekoälytulosten käytöstä, ellei kyseessä ole tahallisuus tai törkeä huolimattomuus.'] },
      { title: '7. Laittoman sisällön luomisen rajoitukset', content: ['Palvelu voi rajoittaa tai kieltäytyä luomasta sellaista sisältöä kuin:', '• Laitonta toimintaa edistävä sisältö, kunnianloukkaus, tekijänoikeusloukkaukset', '• Yksityisyyden loukkaaminen, pornografia, viha- ja syrjivä sisältö', '• Haittaohjelmien luominen, hakkeroinnin tuki, sovellettavia lakeja rikkova sisältö'] },
      { title: '8. Tekoälypalvelun muutokset', content: 'Operaattori voi muuttaa tekoälypalvelun toimintoja tai tulosten ominaisuuksia tekoälymallin muutosten, suorituskyvyn parannusten tai turvallisuustarpeiden vuoksi.' },
      { title: '9. Lopullinen tarkistus', content: 'Jäsenten on tarkasteltava tekoälyn tuottamia tuloksia lopullisesti ja päätettävä itse niiden käytöstä; vastuu niiden käyttämisestä tärkeiden päätösten perustana kuuluu jäsenelle itselleen.' }
    ]
  }
};

export default function AIDisclaimerPage() {
  const router = useRouter();
  const [lang, setLang] = useState('ko');

  const currentDisclaimer = disclaimerTranslations[lang] || disclaimerTranslations.ko;

  const handleBack = () => {
    router.push('/signup'); 
  };

  return (
    <div className="max-w-3xl mx-auto px-4 py-12 font-sans text-gray-800">
      {/* 상단 네비게이션 및 언어 선택 드롭다운 */}
      <div className="flex justify-between items-center mb-8 pb-4 border-b border-gray-200">
        <h1 className="text-2xl font-bold text-gray-900">{currentDisclaimer.title}</h1>
        
        <div className="flex items-center gap-3">
          <select
            value={lang}
            onChange={(e) => setLang(e.target.value)}
            className="px-3 py-1.5 text-sm rounded-lg border border-gray-300 bg-white text-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="ko">한국어 (Korean)</option>
            <option value="en">English</option>
            <option value="ja">日本語 (Japanese)</option>
          </select>
        </div>
      </div>

      {/* 안내 문구 */}
      <div className="bg-blue-50 border-l-4 border-blue-500 p-4 mb-8 rounded-r-lg">
        <p className="text-blue-900 leading-relaxed">{currentDisclaimer.intro}</p>
      </div>

      {/* 본문 섹션 리스트 */}
      <div className="space-y-6 mb-12">
        {currentDisclaimer.sections.map((section, index) => (
          <div key={index} className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
            <h2 className="text-lg font-semibold text-gray-900 mb-3">{section.title}</h2>
            {Array.isArray(section.content) ? (
              <ul className="space-y-2 text-gray-700 text-sm leading-relaxed">
                {section.content.map((item, idx) => (
                  <li key={idx}>{item}</li>
                ))}
              </ul>
            ) : (
              <p className="text-gray-700 text-sm leading-relaxed">{section.content}</p>
            )}
          </div>
        ))}
      </div>

      {/* 돌아가기 버튼 (이미지와 같은 파란색 배경 적용) */}
      <div className="flex justify-center items-center w-full mt-12 mb-8">
        <button
          onClick={handleBack}
          className="px-8 py-3.5 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-lg transition-colors shadow-md"
        >
          {currentDisclaimer.backBtn}
        </button>
      </div>
    </div>
  );
}